### ISSUE TITLE
C Program to Compute Quotient and Remainder

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#1]
Write a program to find the quotient and remainder of two numbers.

**Sample output:**

_Enter two numbers A and B : 25 4
Quotient when A/B is: 6
Remainder when A/B is: 1_

**Comment by PragyaSharma11** [comment]
#include <stdio.h>

int main()

{
int a,b;
printf("enter the value of a=");
scanf("%d",&a);
printf("enter the value of b=");
scanf("%d",&b);
printf("quotient=%d\n",a/b);
printf("remainder=%d",a%b);

return 0;
}
![image](https://user-images.githubusercontent.com/113793494/221220210-31f75802-9479-4e30-93a1-845690b1af49.png)
