### ISSUE TITLE
Menu driven program using switch case

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#10]
Write a menu-driven program using Switch case to calculate the following: 
1. Area of circle 
2. Area of square 
3. Area of sphere

**Comment by PragyaSharma11** [comment]
#include <stdio.h>
int main()
{
    int choice, radius, length, breadth, side;
    float area;
    printf("\n Press 1 to calculate area of Circle \n Press 2 to calculate area of Rectangle \n Press 3 to calculate area of Square \n Press 4 to Exit");
    printf("\n Enter your choice:");
    scanf("%d", &choice);
    switch (choice)
    {
    case 1:
        printf("\n Enter radius:");
          scanf("%d", &radius);
          area = 3.14 * radius * radius;
          printf("\n Area of circle: %f", area);
            break;
    case 2:
        printf("\n Enter length:");
          scanf("%d", &length);
          printf("\n Enter breadth:");
          scanf("%d", &breadth);
          printf("\n Area of rectangle: %d", length * breadth);
            break;
    case 3:
        printf("\n Enter Side:");
          scanf("%d", &side);
          printf("\n Area of square: %d", side * side);
            break;
    case 4:
        return 0;
    default:
        printf("\n wrong choice");
    }
    return 0;
}
![image](https://user-images.githubusercontent.com/113793494/222061179-030032bd-8a10-499c-b580-a908bf9f7d95.png)

**Comment by sivaranjini0311** [comment]
area = 3.14 * radius * radius;

Don't use direct values in code, use MACRO.

**Comment by PragyaSharma11** [comment]
#include <stdio.h>
#define PI 3.14
int main()
{
int choice, radius, length, breadth, side;
float area;
printf("\n Press 1 to calculate area of Circle \n Press 2 to calculate area of Rectangle \n Press 3 to calculate area of Square \n Press 4 to Exit");
printf("\n Enter your choice:");
scanf("%d", &choice);
switch (choice)
{
case 1:
printf(" Enter radius:");
scanf("%d", &radius);
area = PI * radius * radius;
printf(" Area of circle: %f", area);
break;
case 2:
printf("\n Enter length:");
scanf("%d", &length);
printf("\n Enter breadth:");
scanf("%d", &breadth);
printf("\n Area of rectangle: %d", length * breadth);
break;
case 3:
printf("\n Enter Side:");
scanf("%d", &side);
printf("\n Area of square: %d", side * side);
break;
case 4:
return 0;
default:
printf("\n wrong choice");
}
return 0;
}
![image](https://user-images.githubusercontent.com/113793494/223132034-66bbf09f-2081-4c43-9047-f7ebeb012449.png)
