### ISSUE TITLE
C Program to check whether the given integer is positive or negative

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#2]
Get an integer and print the output as positive or negative according to the input integer.

**Sample outputs:**

**Output 1:**
_Enter a number:
0
0 is neither positive nor negative_

**Output 2:**
_Enter a number:
-99
-99 is a negative number_

**Output 3:**
_Enter a number:
5
5 is a positive number_

**Comment by PragyaSharma11** [comment]
#include <stdio.h>

int main()

{
int a;
printf("enter the value of a=");
scanf("%d",&a);
if(a<0)
{
printf("%d is negative",a);
}
else if(a>0)
{
printf("%d is positive",a);
}
else if(a==0)
{
printf("0 is neither positive nor negative");
}

return 0;
}
![image](https://user-images.githubusercontent.com/113793494/221220656-69a19432-7da4-4eee-9c01-e74e79ffdcb5.png)
![image](https://user-images.githubusercontent.com/113793494/221220825-3f029d18-cb46-4ad5-8d2f-ad61abdb1154.png)
![image](https://user-images.githubusercontent.com/113793494/221221011-52553ecd-8370-4ec9-9d0f-07a8dc9e742b.png)
