### ISSUE TITLE
Find first non-repeating character of given String

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#3]
Given a string S consisting of lowercase Latin Letters, the task is to find the first non-repeating character in S.

**Sample Output:**

_Input: “character”
Output: h
Explanation: As ‘h’ is first character in the string which does not repeat._

_Input: “Remember"
Output: b
Explanation: As ‘b’ is first character in the string which does not repeat._

**Comment by PragyaSharma11** [comment]
#include <stdio.h>
#include <string.h>

int main(void) {

char str[100] = "remember";
int len = strlen(str);
int flag;
for(int i = 0; i < len; i++)
{
flag = 0;
for(int j = 0; j < len; j++)
{
if((str[i] == str[j]) && (i != j)) {
flag = 1;
break;
}
}
if (flag == 0) {
printf("First non-repeating character is %c",str[i]);
break;
}
}
if (flag == 1) {
printf("Didn't find any non-repeating character");
}
return 0;
}
![image](https://user-images.githubusercontent.com/113793494/221222981-51862a17-668e-4883-9668-b8604c2cb5b1.png)
![image](https://user-images.githubusercontent.com/113793494/221223071-ec86d796-a61b-45da-ac3d-1f112cc7b863.png)
