### ISSUE TITLE
C Program to Count the Number of Vowels, Consonants, digits and whitespaces

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#5]
Program to count vowels, consonants, digits and whitespaces.

**Sample Output:**
_Enter a line of string: C++ 20 is the latest version of C++ yet.
Vowels: 9
Consonants: 16
Digits: 2
White spaces: 8_

**Comment by PragyaSharma11** [comment]
#include <stdio.h>
int main() {

char line[150];
int vowels, consonant, digit, space;
vowels = consonant = digit = space = 0;
printf("Enter a line of string: ");
fgets(line, sizeof(line), stdin);
for (int i = 0; line[i] != '\0'; ++i) {
line[i] = tolower(line[i]);
if (line[i] == 'a' || line[i] == 'e' || line[i] == 'i' ||
line[i] == 'o' || line[i] == 'u')
{
++vowels;
}
else if ((line[i] >= 'a' && line[i] <= 'z')) {
++consonant;
}
else if (line[i] >= '0' && line[i] <= '9') {
++digit;
}
else if (line[i] == ' ') {
++space;
}
}
printf("Vowels: %d", vowels);
printf("\nConsonants: %d", consonant);
printf("\nDigits: %d", digit);
printf("\nWhite spaces: %d", space);
return 0;
}
![image](https://user-images.githubusercontent.com/113793494/221222135-96ac051d-06fa-40db-ab16-2e4ba8be44af.png)
![image](https://user-images.githubusercontent.com/113793494/221222218-490d6b2f-5688-40f5-ad47-8b304c67d996.png)
