### ISSUE TITLE
C Program to Remove all Characters in a String Except Alphabets

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#6]
Remove Characters in String Except Alphabets

**Sample Output:**
_Enter a string: 4'.H@-\9i4./
Output String: Hi_

**Comment by PragyaSharma11** [comment]
#include<stdio.h>
#include<string.h>
int main()
{
char str[20];
int i, j;
printf("\nEnter a string :");
gets(str);
for(i = 0; str[i] != '\0'; ++i)
{
while (!( (str[i] >= 'a'&& str[i] <= 'z') || (str[i] >= 'A' && str[i] <= 'Z') || str[i] == '\0') )
{
for(j = i; str[j] != '\0'; ++j)
{
str[j] = str[j+1];
}
str[j] = '\0';
}
}
printf("\nResultant String :");
puts(str);
return 0;
}
![image](https://user-images.githubusercontent.com/113793494/221221631-a7c1403b-203b-41f0-91c2-d634a92f0783.png)
