### ISSUE TITLE
Write a C program to find the maximum and minimum in the given three numbers using the conditional operator.

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#8]

**Comment by PragyaSharma11** [comment]
#include <stdio.h>  
   
int main()  {  
    int a, b, c, max;  
    printf("Enter Three Integers\n");  
    scanf("%d %d %d", &a, &b, &c);  
     
    max = (a > b) ? ((a > c) ? a : c) : ((b > c) ? b : c);
    printf("Maximum Number is = %d\n", max);  
   
    return 0;  
}
![image](https://user-images.githubusercontent.com/113793494/222053325-f996ebed-0953-4942-83c7-4c59d6ecf767.png)

**Comment by sivaranjini0311** [comment]
Minimum in the given three numbers missing?

**Comment by PragyaSharma11** [comment]
#include <stdio.h>
int main() {
int a, b, c, max,min;
printf("Enter Three Integers\n");
scanf("%d %d %d", &a, &b, &c);
max = (a > b) ? ((a > c) ? a : c) : ((b > c) ? b : c);
min= (a < b) ? (( a < c) ? a : c) :(( b < c) ? b : c);
printf("Maximum Number is = %d\n", max); 
printf("Minimum Number is = %d\n", min);

return 0;  
}
![image](https://user-images.githubusercontent.com/113793494/223134715-ca8a6600-6413-4755-a374-1793874e418b.png)
