### ISSUE TITLE
Write a C program to test if a number is a power of 2 using function and conditional operator.

### ISSUE THREAD

**Issue by sivaranjini0311** [hari-eur/Pragya-Sharma---Siva-Ranjini#9]

**Comment by PragyaSharma11** [comment]
#include <stdio.h>
int main()
{
    int n;
    printf("enter any number:");
    scanf("%d",&n);
    int res= n & (n-1);
    (res == 0)?printf("power of 2\n"):printf("not the power of 2\n");
    return 0;
}
![image](https://user-images.githubusercontent.com/113793494/222059951-9f9c2b4d-1266-4510-9d24-cad00d07d1a1.png)

**Comment by sivaranjini0311** [comment]
int res= n & (n-1);

Have a practice of making variable declaration at the start of function itself.

**Comment by PragyaSharma11** [comment]
okay mam, I won't repeat it again...
